import Head from 'next/head';

import AboutMe from '../src/components/AboutMe';
import Hero from '../src/components/Hero';
import AllProjects from '../src/components/projects/Projects';
import ToolBelt from '../src/components/ToolBelt';

export default function Home() {
  return (
    <>
      <Head>
        <title>Tyson Suttle</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <Hero />
      <article className="mt-10 container space-y-32">
        <AboutMe />
        <ToolBelt />
        <AllProjects />
      </article>
    </>
  );
}
