import Head from 'next/head';
import Image from 'next/image';

import AboutMe from '../src/components/AboutMe';
import Hero from '../src/components/Hero';
import NavBar from '../src/components/NavBar';
import AllProjects from '../src/components/projects/Projects';
import ToolBelt from '../src/components/ToolBelt';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <NavBar />
      <Hero />
      <main className="mt-10 max-w-screen-lg mx-auto px-10 md:px-0">
        <AboutMe />
        <ToolBelt />
        <AllProjects />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
