import Head from 'next/head';
import Image from 'next/image';

import AboutMe from '../src/components/AboutMe';
import Footer from '../src/components/Footer';
import Hero from '../src/components/Hero';
import NavBar from '../src/components/NavBar';
import AllProjects from '../src/components/projects/Projects';
import ToolBelt from '../src/components/ToolBelt';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <NavBar />
      <Hero />
      <main className="mt-10 container space-y-32">
        <AboutMe />
        <ToolBelt />
        <AllProjects />
      </main>
      <Footer />
    </>
  );
}
